### ISSUE TITLE
python-semantic-release appears to reference wrong package

### ISSUE THREAD

**Issue by alandtse** [pyupio/safety-db#2320] opened 2020-08-23 04:51 UTC
I've recently started getting a safety error for python-semantic-release.
```bash
| REPORT                                                                       |
| checked 108 packages, using default DB                                       |
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| python-semantic-release    | 6.1.0     | <15.13.25                | 37516    |
+==============================================================================+
```

However, this is nonsensical since [python-semantic-release](https://pypi.org/project/python-semantic-release/) is only on version 7.2.2 as of this submission. It's possible the database is confusing python-semantic-release with the JavaScript project [semantic-release](https://github.com/semantic-release/semantic-release) which is totally unrelated.

**Comment by harlekeyn** [comment] 2020-08-23 23:24
Duplicate of #2315

**Closed by harlekeyn** 2020-08-23 23:24 UTC
