### ISSUE TITLE
simple_salesforce < 1.0.0 is incorrectly marked as insecure 

### ISSUE THREAD

**Issue by soylent** [pyupio/safety-db#2306] opened 2020-04-16 22:41 UTC
Please see https://github.com/simple-salesforce/simple-salesforce/blob/1ebee0085b27ab5f9181a5e691fb8dc9fdc90163/CHANGES#L10:L11

**Comment by harlekeyn** [comment] 2020-04-17 00:42
Would you be able to help me understand what the sentence _"Make the minimum version of requests v 2.22.0, allowing us to remove requests[security]"_ means?

Here is how I am interpreting the first part:
The library `simple-salesforce` bumped their dependency on the library `requests` to version 2.22.0. This is good because the library `requests` is confirmed to be not secure prior to 2.22.0. Hence, the library `simple-salesforce` was not secure prior to 1.0.0.

The second part (_"allowing us to remove requests"_) is not clear to me. Whatever the reason was to remove `requests`, it apparently was still included (and not secure) prior to 1.0.0. So, how would this make simple-salesforce <1.0.0 incorrectly marked as not secure?

**Comment by soylent** [comment] 2020-04-17 18:17
That is false.

It simply means that they have changed the requirements from `requests[security]` to `requests>=2.22.0` because they no longer support python < 3.5.

**Comment by harlekeyn** [comment] 2020-04-21 21:28
Thanks for the clarification. You are saying it went from a secure version of `requests` to another secure version of `requests`.

As someone unfamiliar with the `requests` library, I had no idea what was meant with "`requests[security]`".

I have updated the DB.

**Closed by harlekeyn** 2020-04-21 21:28 UTC
