### ISSUE TITLE
Install and usage steps do not seem to work

### ISSUE THREAD

**Issue by peacepirate** [pyupio/safety-db#2273] opened 2018-08-03 00:35 UTC
I am just trying this out, and not sure if I am missing anything. But seems like the steps do not work for a new python environment at least. I am not sure if the issue is with packaging the data directory in the package or not yet, but seems that way.

`python3 -m venv .env`
`source .env/bin/activate`
`pip install safety-db`
`python -c "import safety_db"`

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/virtualenvs/api/lib/python3.6/site-packages/safety_db.py", line 13, in <module>
    with open("data/insecure.json") as __f:
IOError: [Errno 2] No such file or directory: 'data/insecure.json'

Edit: The traceback output was using a different environment and has been fixed, but the issue persists either way.

**Comment by volans-** [comment] 2018-08-23 20:57
I can confirm the error, and it's because the files are not installed in the virtualenv. It seems it was fixed in #2268 but it has not yet released into PyPI.

**Comment by rafaelpivato** [comment] 2020-04-15 22:56
Should be fixed now.

**Closed by rafaelpivato** 2020-04-15 22:56 UTC
Labels: bug
